server:
  port: 9195
 
 
spring:  application:    name: CONFIG-SERVER
  cloud:    config:      server:        git:
          uri: https://github.com/indrajeetydv/cloud-config-server
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
   preferIpAddress: true