spring:
  application:
    name: indrajeet-yadav

server:  port: 8080
  
eureka:  client:    register-with-eureka: true
    fetch-registry: true    service-url:     default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:    prefer-ip-address: true