#server:
#  port: 9191


server:  port: ${PORT:0}
   
spring:  h2:    console:      enabled: true
  datasource:    url: jdbc:h2:mem:testdb
  application:    name: PAYMENT-SERVICE
  zipkin:
    base-url: http://localhost:9411/
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#   preferIpAddress: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
#   instance-id: ${spring.application.name}:${random.uuid}