server:
  port: 9192
 
 
spring:  h2:    console:      enabled: true
  datasource:    url: jdbc:h2:mem:testdb
  application:    name: ORDER-SERVICE
  zipkin:
    base-url: http://localhost:9411/
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#   preferIpAddress: true